services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - path: .env
        required: false
    command: tail -f /dev/null
  db:
    image: mysql:8.0.29
    # this is required becuse of
    # django.db.utils.OperationalError: (2061, 'RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support')
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - path: .env
        required: false
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 5

  # This is a convienient utility app to manage the database
  # It's only used in development and can be removed if not required.
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
